### ISSUE TITLE
Error when trying ot start the application

### ISSUE THREAD

**Issue by ariestai** [RowanHall/desktop-youtube-music#1]
![Annotation 2019-10-19 143740](https://user-images.githubusercontent.com/56472203/67139037-08443680-f27e-11e9-823f-b2c452a6389b.png)
When I click OK the error windows basically closes and then jumps out again.
And then it enters an infinite loop, I need to use the task manager to close it.
I really appreciate your work but... it just doesn't work.

**Comment by RowanHall** [comment]
The project's servers are currently shutdown, hence the "CONNECTING" error. 

The project may be revived if I have enough time & money, expect an update in the YouTube Music subreddit if anything happens. My reddit is u/SoLoDas

**Comment by wayLANder3** [comment]
Any news?
